# fly.toml app configuration file generated for station-wallet-screening on 2023-11-03T13:29:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "station-wallet-screening"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  path = "/0x000000000000000000000000000000000000dEaD"
